function createfigureBfield(X1, Y1, Z1, xdata1, ydata1, zdata1, zdata2, XMatrix1, YMatrix1, ZMatrix1, xdata2, ydata2, zdata3, ydata3, ydata4, ydata5, ydata6, ydata7, ydata8, X2, Z2, xdata3, ydata9, zdata4, xdata4, zdata5, xdata5, ydata10, zdata6, X3, Y2, Z3, U1, V1, W1)
%CREATEFIGURE(X1, Y1, Z1, xdata1, ydata1, zdata1, zdata2, XMatrix1, YMatrix1, ZMatrix1, xdata2, ydata2, zdata3, ydata3, ydata4, ydata5, ydata6, ydata7, ydata8, X2, Z2, xdata3, ydata9, zdata4, xdata4, zdata5, xdata5, ydata10, zdata6, X3, Y2, Z3, U1, V1, W1)
%  X1:  scatter3 x
%  Y1:  scatter3 y
%  Z1:  scatter3 z
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  ZDATA2:  surface zdata
%  XMATRIX1:  matrix of x data
%  YMATRIX1:  matrix of y data
%  ZMATRIX1:  matrix of z data
%  XDATA2:  surface xdata
%  YDATA2:  surface ydata
%  ZDATA3:  surface zdata
%  YDATA3:  surface ydata
%  YDATA4:  surface ydata
%  YDATA5:  surface ydata
%  YDATA6:  surface ydata
%  YDATA7:  surface ydata
%  YDATA8:  surface ydata
%  X2:  vector of x data
%  Z2:  vector of z data
%  XDATA3:  surface xdata
%  YDATA9:  surface ydata
%  ZDATA4:  surface zdata
%  XDATA4:  surface xdata
%  ZDATA5:  surface zdata
%  XDATA5:  surface xdata
%  YDATA10:  surface ydata
%  ZDATA6:  surface zdata
%  X3:  quiver3 x
%  Y2:  quiver3 y
%  Z3:  quiver3 z
%  U1:  quiver3 u
%  V1:  quiver3 v
%  W1:  quiver3 w

%  Auto-generated by MATLAB on 12-Jan-2020 16:45:44

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
axis off
hold(axes1,'on');

% Create scatter3
scatter3(X1,Y1,Z1);

% Create surf
surf(xdata1,ydata1,zdata1,'Parent',axes1,'FaceColor',[1 0 0],...
    'EdgeColor',[1 0 0]);

% Create surf
surf(xdata1,ydata1,zdata2,'Parent',axes1,'FaceColor',[0 0 1],...
    'EdgeColor',[0 0 1]);

% Create light
light('Parent',axes1);

% Create multiple lines using matrix input to plot3
plot31 = plot3(XMatrix1,YMatrix1,ZMatrix1,'Parent',axes1,'LineWidth',1,...
    'Color',[0 0 0]);
set(plot31(1),'LineWidth',3,'Color',[0 1 0]);
set(plot31(2),'LineWidth',3,'Color',[1 0 0]);

% Create surf
surf(xdata2,ydata2,zdata3,'Parent',axes1,'FaceColor',[0 0 0]);

% Create surf
surf(xdata1,ydata3,zdata1,'Parent',axes1,'FaceColor',[1 0 0],...
    'EdgeColor',[1 0 0]);

% Create surf
surf(xdata1,ydata3,zdata2,'Parent',axes1,'FaceColor',[0 0 1],...
    'EdgeColor',[0 0 1]);

% Create light
light('Parent',axes1);

% Create surf
surf(xdata2,ydata4,zdata3,'Parent',axes1,'FaceColor',[0 0 0]);

% Create surf
surf(xdata1,ydata5,zdata1,'Parent',axes1,'FaceColor',[1 0 0],...
    'EdgeColor',[1 0 0]);

% Create surf
surf(xdata1,ydata5,zdata2,'Parent',axes1,'FaceColor',[0 0 1],...
    'EdgeColor',[0 0 1]);

% Create light
light('Parent',axes1);

% Create surf
surf(xdata2,ydata6,zdata3,'Parent',axes1,'FaceColor',[0 0 0]);

% Create surf
surf(xdata1,ydata7,zdata1,'Parent',axes1,'FaceColor',[1 0 0],...
    'EdgeColor',[1 0 0]);

% Create surf
surf(xdata1,ydata7,zdata2,'Parent',axes1,'FaceColor',[0 0 1],...
    'EdgeColor',[0 0 1]);

% Create light
light('Parent',axes1);

% Create surf
surf(xdata2,ydata8,zdata3,'Parent',axes1,'FaceColor',[0 0 0]);

% Create plot3
plot3(X2,X2,Z2,'LineWidth',3,'Color',[0 0 1]);

% Create surf
surf(xdata3,ydata9,zdata4,'Parent',axes1,'FaceColor',[1 0 0],...
    'EdgeColor',[1 0 0]);

% Create surf
surf(xdata4,xdata3,zdata5,'Parent',axes1,'FaceColor',[0 1 0],...
    'EdgeColor',[0 1 0]);

% Create surf
surf(xdata4,ydata9,xdata3,'Parent',axes1,'FaceColor',[0 0 1],...
    'EdgeColor',[0 0 1]);

% Create surf
surf(xdata5,ydata10,zdata6,'Parent',axes1,'FaceColor',[0 0 0]);

% Create quiver3
quiver3(X3,Y2,Z3,U1,V1,W1);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-0.08 0.08]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.08 0.08]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-0.08 0.08]);
view(axes1,[-37.5 30]);
% Set the remaining axes properties
set(axes1,'CameraViewAngle',2.61209557412855,'DataAspectRatio',[1 1 1]);
