function [fitresult, gof, p1, p2] = createFit(X, N, tit)
%CREATEFIT(X,N)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : X
%      Y Output: N
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Jun-2021 13:08:51
if(nargin < 3)
  tit = 'untitled fit';
end

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( X, N );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );
p1 = fitresult.p1;
p2 = fitresult.p2;

% Plot fit with data.
h = plot( fitresult, xData, yData );
legend( h, 'N vs. X', tit, 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
title(tit);
xlabel( 'X', 'Interpreter', 'none' );
ylabel( 'N', 'Interpreter', 'none' );
grid on


